### ISSUE TITLE
Fatal Mysqli error bei abschicken eines Kommentars

### ISSUE THREAD

**Issue by WackyPete** [dastrinken/clanms#119]
**Describe the bug**
Fatal Mysqli error bei abschicken eines Kommentars, Kommentar wird aber korrekt in die Datenbank geschrieben

**To Reproduce**
1. Go to Blog
2. Write a Comment
3. Send your Comment

**Error**
Fatal error
: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-5, 5' at line 6 in C:\xampp\htdocs\clanms-dev\clanms\content\newsblog\newsblog_functions.php:50 Stack trace: #0 C:\xampp\htdocs\clanms-dev\clanms\content\newsblog\newsblog_functions.php(50): mysqli->query('SELECT news.id,...') #1 C:\xampp\htdocs\clanms-dev\clanms\sitemenu.php(7): showAllNews() #2 C:\xampp\htdocs\clanms-dev\clanms\index.php(43): require('C:\\xampp\\htdocs...') #3 {main} thrown in
C:\xampp\htdocs\clanms-dev\clanms\content\newsblog\newsblog_functions.php
on line
50

**Expected behavior**
Refresh der Blogseite

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome

**Additional context**
Denke kann irgendwie an der Pagination der Artikel liegen

**Comment by dastrinken** [comment]
Fixed! ;)
