### ISSUE TITLE
Artikel in vergangenheit

### ISSUE THREAD

**Issue by Usurper321** [dastrinken/clanms#76]
**Describe the bug**
man darf kein Artikel in der vergangenheit schreiben 

**To Reproduce**
1. Go to admin dashboard
2. Click on neu
4. wähl eine beliebige datum ein 
5. speichern

**Screenshots**
![image](https://user-images.githubusercontent.com/97109375/159707657-0bc90554-5800-4c73-8fb8-fa351acfdb4d.png)

**Comment by dastrinken** [comment]
Guter Hinweis! Problem mit Angabe von "min"-Wert date('Y-m-d\TH:i:s') gelöst.
